### ISSUE TITLE
Is the LLM Qwen1.5-7B or Qwen2-7B?

### ISSUE THREAD

**Issue by Alex-Songs** [QwenLM/Qwen2-Audio#1]
Hello，
   Is the LLM Qwen1.5-7B or Qwen2-7B?

**Comment by faychu** [comment]
The LLM is Qwen-7B.

**Comment by SoshyHayami** [comment]
@faychu 
Is it possible to release the training | finetuning (not Lora, but fft) code as well? 
there's a lot of Ideas I wanted to try out with the original model but it wasn't easy to do so.
