### ISSUE TITLE
about timestamps

### ISSUE THREAD

**Issue by ChuxiJ** [QwenLM/Qwen2-Audio#14]
What is the prompt to let the model output the timestamps in the ASR task like the whisper model?

Can we have more prompt guidance?

**Comment by kaixindelele** [comment]
字幕asr提取，好像就可以，我试了一下，效果还挺好的

**Comment by thhung** [comment]
@ChuxiJ Did you manage to do it? Could you share with me? I am looking for this but could not find they mention it anywhere.

**Comment by SetoKaiba** [comment]
> 字幕asr提取，好像就可以，我试了一下，效果还挺好的

能给一个具体的prompt吗？还是就"字幕asr提取"就是prompt？
