### ISSUE TITLE
关于qwen2-audio的微调和量化，什么时候开始支持

### ISSUE THREAD

**Issue by Liufeiran123** [QwenLM/Qwen2-Audio#16]
关于qwen2-audio的微调和量化，什么时候开始支持

**Comment by faychu** [comment]
微调和量化我们正在开发中，微调可以先参考Modelscope的实践：https://github.com/modelscope/ms-swift/issues/1653

**Comment by Lollipop** [comment]
使用accelerate微调代码：#61
