### ISSUE TITLE
demo not work

### ISSUE THREAD

**Issue by ChuxiJ** [QwenLM/Qwen2-Audio#28]
File "/root/miniconda3/envs/qwen_audio/lib/python3.10/site-packages/transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1102, in _merge_input_ids_with_audio_features
    raise ValueError(
ValueError: The input provided to the model are wrong. The number of audio tokens is tensor([1], device='cuda:0') while the number of audio given to the model is 1. This prevents correct indexing and breaks batch generation.
^CKeyboard interruption in main thread... closing server.

gpu environment: 8x4090
input: a 20s audio clip and a instruction prompt

![image](https://github.com/user-attachments/assets/bb43ae08-1afe-4514-b766-8d8f0b273a37)

**Comment by zzlgreat** [comment]
Same problem, how did you slove it?

**Comment by bingyunsky** [comment]
Same problem。

**Comment by ChuxiJ** [comment]
The issue was resolved by setting CUDA_VISIBLE_DEVICES to specify a single GPU card.

**Comment by juhayna-zh** [comment]
I encountered a similar problem with the same error as this one, and this issue #42 solved my problem.
