### ISSUE TITLE
system角色不起作用

### ISSUE THREAD

**Issue by HiXxxSss** [QwenLM/Qwen2-Audio#34]
```
conversation = [
    {'role': 'system', 'content': "不论用户用什么语言与你沟通，你都要用日文回答用户。"}, 
    {"role": "user", "content": [
        {"type": "audio", "audio_url": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen2-Audio/audio/glass-breaking-151256.mp3"},
        {"type": "text", "text": "这是什么声音"},
    ]},
]
```
上面的对话，模型似乎接收不到system的内容

**Comment by aimerib** [comment]
I see you closed this as completed @HiXxxSss , but I am having the exact same problem. If I set a system prompt, any system prompt, Qwen just ignores it. As a test, I did a version of yours, and set my system prompt to this:

conversation = [
    {'role': 'system', 'content': "Não importa em que idioma o usuário está falando, você sempre responde em português brasileiro."}, 
    {"role": "user", "content": [
        {"type": "text", "text": "Who are you?"},
    ]},
]

![Screenshot 2024-12-04 at 11 36 28 AM](https://github.com/user-attachments/assets/8ff21442-d3e6-4ef7-acde-c79a0d3ec84a)

I can send an audio asking the same question and it will reply in the exact same way (simply did a text here to simplify the code, but my code looks exactly like the demo except for adding a system prompt.

I have applied the chat template just like in the demo as well. Is this supposed to be supported?
