### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by QianguoS** [QwenLM/Qwen2-Audio#40]
After installing the latest version of transformers as requested, I encountered the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

the code run util:
inputs_embeds = self.get_input_embeddings()(input_ids)

**Comment by chocWan** [comment]
i have the same issue

**Comment by chocWan** [comment]
![image](https://github.com/user-attachments/assets/226a9fa2-9295-485e-8829-060a3de456b4)
solved
