### ISSUE TITLE
执行Audio Analysis Inference示例代码时报错

### ISSUE THREAD

**Issue by xiaodiandian1234** [QwenLM/Qwen2-Audio#42]
执行Audio Analysis Inference的例子：
conversation = [
    {'role': 'system', 'content': 'You are a helpful assistant.'}, 
    {"role": "user", "content": [
        {"type": "audio", "audio_url": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen2-Audio/audio/glass-breaking-151256.mp3"},
        {"type": "text", "text": "What's that sound?"},
    ]},
    {"role": "assistant", "content": "It is the sound of glass shattering."},
    {"role": "user", "content": [
        {"type": "text", "text": "What can you do when you hear that?"},
    ]},
    {"role": "assistant", "content": "Stay alert and cautious, and check if anyone is hurt or if there is any damage to property."},
    {"role": "user", "content": [
        {"type": "audio", "audio_url": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen2-Audio/audio/1272-128104-0000.flac"},
        {"type": "text", "text": "What does the person say?"},
    ]},
]
text = processor.apply_chat_template(conversation, add_generation_prompt=True, tokenize=False)

报错：
Traceback (most recent call last):
  File "Qwen2_Audio_7B_Instruct/infer/example2/infer2.py", line 40, in <module>
    generate_ids = model.generate(**inputs, max_length=256)
  File "site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1209, in forward
    inputs_embeds, attention_mask, labels, position_ids, _ = self._merge_input_ids_with_audio_features(
  File "transformers/models/qwen2_audio/modeling_qwen2_audio.py", line 1045, in _merge_input_ids_with_audio_features
    token_placeholder_num[special_audio_token_mask] = num_audio_tokens.long() - 1
RuntimeError: shape mismatch: value tensor of shape [2] cannot be broadcast to indexing result of shape [0]

debug了一下，num_audio_tokens.long() 的值为[101, 146]，好像是无法赋值到左边。

另外看这行代码：text = processor.apply_chat_template(conversation, add_generation_prompt=True, tokenize=False)，生成的text结果，里面没有了audio tag，这样会导致special_audio_token_mask这个变量都是false。如果special_audio_token_mask总是false，是否会造成audio_features merge不进去，即最终没有利用到audio的信息？

感谢回复！

**Comment by xiaodiandian1234** [comment]
抱歉是我的问题，问题原因是：为了可以读本地audio文件，把conversation中的audio_url改为了audio_path，这样改了之后，processor.apply_chat_template返回的结果里就缺少了AUDIO tag。


抱歉打扰了

**Comment by xiaodiandian1234** [comment]
抱歉是我的问题，问题原因是：为了可以读本地audio文件，把conversation中的audio_url改为了audio_path，这样改了之后，processor.apply_chat_template返回的结果里就缺少了AUDIO tag。


抱歉打扰了

**Comment by mmiumiu** [comment]
您好，请问读取本地audio文件怎么补充上AUDIO tag？可以给个代码示例吗

**Comment by xiaodiandian1234** [comment]
简单方法是conversation中的audio_url这个key不要改动，只是把其内容改为本地audio文件的路径，后面在根据本地文件路径去读wav数据。

**Comment by mmiumiu** [comment]
好的感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月4日(周三) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen2-Audio] 执行Audio Analysis Inference示例代码时报错 (Issue #42)




 
简单方法是conversation中的audio_url这个key不要改动，只是把其内容改为本地audio文件的路径，后面在根据本地文件路径去读wav数据。
