### ISSUE TITLE
cannot download MELD converted file

### ISSUE THREAD

**Issue by cminus01** [QwenLM/Qwen2-Audio#65]
Hello, I want to evaluate SER task for Qwen2-Audio,but I found that the provided MELD converted files in EVALUATION.md cannot be accessed. 
The link is "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen2-Audio/evaluation/meld_eval.jsonl", and the error information is as follow: 
<img width="914" alt="image" src="https://github.com/user-attachments/assets/86039f6b-dad7-414a-9b1f-7108ea167c97">

**Comment by MeowsQAQ** [comment]
same issue

**Comment by cminus01** [comment]
> same issue

Now it can be downloaded

**Comment by cminus01** [comment]
The author has fixed this issue now
