### ISSUE TITLE
Voice chat time cost not less than FunASR + Qwen2?

### ISSUE THREAD

**Issue by Arnold134777** [QwenLM/Qwen2-Audio#69]
I tested it in two scenarios: QWEN2-audio and  FunASR -> text -> Qwen2.

Time-consuming analysis is as follows：no better?

<img width="711" alt="image" src="https://github.com/user-attachments/assets/41719ca4-0e09-4504-9144-34baf6785f25">

**Comment by Liufeiran123** [comment]
推理时间不是最关键的点吧。

**Comment by Arnold134777** [comment]
> 推理时间不是最关键的点吧。

并非最关键的点，只是原本以为会节省ASR的时间，但是貌似多了语音编码的时间。
